// src/lib/researchPromptLibraryData.ts

import type { MinLevel } from "./promptLibraryData";

export interface PromptVariant {
  text: string;
  where: string;
  whyHere: string;
}

export interface ResearchPromptEntry {
  id: string;
  name: string;
  minLevel: MinLevel;
  sequenceTag: "Step 1" | "Step 2" | "Step 3";
  when: string;
  note: string;
  text: string;
  inConversation: PromptVariant;
  freshConversation: PromptVariant;
}

export const RESEARCH_PROMPT_LIBRARY: ResearchPromptEntry[] = [

  // ── Step 1 ──────────────────────────────────────────────────────────────────

  {
    id: "self-critique",
    name: "Self-critique",
    minLevel: 1,
    sequenceTag: "Step 1",
    when: "Output may contain unsupported claims, imprecision, or gaps the model itself can flag",
    note: "Models often identify surface issues but miss deeper structural problems. Treat flagged items as a starting point, not a complete audit.",
    text: `I'm going to paste a research output below. Review it carefully. List any claims that appear unsupported, any statements that may be imprecise or overstated, and any areas where you are uncertain about accuracy. Do not defend the output. Focus on what could be wrong.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can critique with full knowledge of what it generated and what it left out.",
      text: `Look back at the output you just produced. List any claims that appear unsupported, any statements that may be imprecise or overstated, and any areas where you are uncertain about accuracy. Do not defend the output. Focus on what could be wrong.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A fresh session removes any tendency to defend prior output; a different model may catch different gaps.",
      text: `I'm going to paste a research output below. Review it carefully. List any claims that appear unsupported, any statements that may be imprecise or overstated, and any areas where you are uncertain about accuracy. Do not defend the output. Focus on what could be wrong.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "confidence-elicitation",
    name: "Confidence elicitation",
    minLevel: 1,
    sequenceTag: "Step 1",
    when: "Output involves factual claims, analysis, or interpretation where confidence varies across items",
    note: "Models are often poorly calibrated. Low stated confidence is useful; high stated confidence is not a reliable indicator of accuracy.",
    text: `I'm going to paste a research output below. For each major claim or result, rate your confidence as High, Medium, or Low and briefly explain why. Flag any claim where you are relying on pattern-matching rather than verified knowledge.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can rate confidence with direct access to what it was drawing on when it generated each claim.",
      text: `Go through the output you just produced. For each major claim or result, rate your confidence as High, Medium, or Low and briefly explain why. Flag any claim where you were relying on pattern-matching rather than verified knowledge.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A different model gives an independent confidence read, which may diverge meaningfully from the original.",
      text: `I'm going to paste a research output below. For each major claim or result, rate your confidence as High, Medium, or Low and briefly explain why. Flag any claim where you are relying on pattern-matching rather than verified knowledge.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "novelty-audit",
    name: "Novelty audit",
    minLevel: 1,
    sequenceTag: "Step 1",
    when: "Output is a hypothesis, research direction, or framing generated by AI",
    note: "AI systems tend to recombine ideas from training data. This probe helps show whether the output is genuinely exploratory or just restates familiar ideas in new language.",
    text: `I'm going to paste a hypothesis or research direction below. For each element, identify whether it represents a genuinely novel combination of ideas or a restatement of an established approach. Flag any directions that appear to closely follow existing work without meaningful extension, and name the work they resemble where possible.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can reflect on the sources it was drawing on when generating the hypothesis, which may reveal anchoring it wouldn't identify from the output text alone.",
      text: `Look back at the hypothesis or research direction you just produced. For each element, identify whether it represents a genuinely novel combination of ideas or a restatement of an established approach. Flag any directions that appear to closely follow existing work without meaningful extension, and name the work they resemble where possible.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A model without prior context approaches the hypothesis as a reader would, making it easier to spot recombination that felt novel in context.",
      text: `I'm going to paste a hypothesis or research direction below. For each element, identify whether it represents a genuinely novel combination of ideas or a restatement of an established approach. Flag any directions that appear to closely follow existing work without meaningful extension, and name the work they resemble where possible.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "scope-audit",
    name: "Scope audit",
    minLevel: 1,
    sequenceTag: "Step 1",
    when: "Output searches, discovers, or synthesises a body of literature or research area",
    note: "AI outputs tend to overrepresent well-published perspectives and omit contradictory or minority findings. This probe helps identify where the output may be narrower than the field.",
    text: `I'm going to paste a literature search or synthesis below. Identify: (1) major perspectives, findings, or research traditions that appear missing or underrepresented; (2) any claims of consensus that may overstate agreement in the field; (3) areas where the evidence base described seems thinner than stated. Where possible, name what is missing rather than just noting the gap.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can identify gaps relative to what it knows about the field, including work it did not cite but is aware of.",
      text: `Look back at the literature search or synthesis you just produced. Identify: (1) major perspectives, findings, or research traditions that appear missing or underrepresented; (2) any claims of consensus that may overstate agreement in the field; (3) areas where the evidence base described seems thinner than stated. Where possible, name what is missing rather than just noting the gap.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A different model may have different coverage and identify blind spots the original model systematically missed.",
      text: `I'm going to paste a literature search or synthesis below. Identify: (1) major perspectives, findings, or research traditions that appear missing or underrepresented; (2) any claims of consensus that may overstate agreement in the field; (3) areas where the evidence base described seems thinner than stated. Where possible, name what is missing rather than just noting the gap.

[PASTE OUTPUT HERE]`,
    },
  },

  // ── Step 2 ──────────────────────────────────────────────────────────────────

  {
    id: "assumption-audit",
    name: "Assumption audit",
    minLevel: 2,
    sequenceTag: "Step 2",
    when: "Output rests on methodological, analytical, or interpretive assumptions that may not hold",
    note: "This focuses on hidden assumptions, not execution errors. A technically correct analysis can still rest on assumptions inappropriate for the specific context.",
    text: `I'm going to paste a research output below. List the key assumptions underlying it. For each assumption, state whether it is explicitly stated, implicitly required, or potentially unjustified given the context. Flag any assumptions that, if wrong, would significantly change the conclusions.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can surface assumptions it made during generation that do not appear in the output text.",
      text: `List the key assumptions underlying the output you just produced. For each assumption, state whether it is explicitly stated in the output, implicitly required, or potentially unjustified given the context. Flag any assumptions that, if wrong, would significantly change the conclusions.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A model reading the output cold may identify assumptions the original model treated as invisible because they were baked into the question.",
      text: `I'm going to paste a research output below. List the key assumptions underlying it. For each assumption, state whether it is explicitly stated, implicitly required, or potentially unjustified given the context. Flag any assumptions that, if wrong, would significantly change the conclusions.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "claim-evidence-audit",
    name: "Claim–evidence audit",
    minLevel: 2,
    sequenceTag: "Step 2",
    when: "Output is research writing, a synthesis, or an interpretation where conclusions may exceed the evidence",
    note: "Facts may be individually correct while conclusions remain overstated. Focus on hedging and causal claims.",
    text: `I'm going to paste a research output below. For each conclusion or interpretive claim, assess whether the level of certainty expressed is warranted by the evidence described or cited. Flag: (1) claims overstated relative to the evidence; (2) causal language used where only correlation or association is established; (3) hedging that is absent or insufficient.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can assess its own hedging choices and identify where it expressed more certainty than it actually had.",
      text: `Review the output you just produced. For each conclusion or interpretive claim, assess whether the level of certainty you expressed is warranted by the evidence you described or cited. Flag: (1) claims you overstated relative to the evidence; (2) causal language you used where only correlation or association is established; (3) places where your hedging was absent or insufficient.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A model reading the output as a critic rather than its author is more likely to flag overconfident framing.",
      text: `I'm going to paste a research output below. For each conclusion or interpretive claim, assess whether the level of certainty expressed is warranted by the evidence described or cited. Flag: (1) claims overstated relative to the evidence; (2) causal language used where only correlation or association is established; (3) hedging that is absent or insufficient.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "reproducibility-probe",
    name: "Reproducibility probe",
    minLevel: 2,
    sequenceTag: "Step 2",
    when: "Output describes an experimental design, protocol, or methods section",
    note: "This focuses on completeness, not scientific validity. AI-generated methods often omit details that a domain expert would include but are necessary for replication.",
    text: `I'm going to paste an experimental design or methods description below. Identify any steps, parameters, conditions, or controls that are described vaguely, ambiguously, or are missing entirely. For each gap, describe specifically what a researcher attempting to replicate this work would need to know that is not currently specified.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can identify omissions relative to what it knows about the methodology but chose not to include.",
      text: `Look back at the experimental design or methods description you just produced. Identify any steps, parameters, conditions, or controls that are described vaguely, ambiguously, or are missing entirely. For each gap, describe specifically what a researcher attempting to replicate this work would need to know that is not currently specified.`,
    },
    freshConversation: {
      where: "In a new conversation, ideally a different model",
      whyHere: "A different model approaching the methods as a replicator will find gaps that the original model assumed were implied.",
      text: `I'm going to paste an experimental design or methods description below. Identify any steps, parameters, conditions, or controls that are described vaguely, ambiguously, or are missing entirely. For each gap, describe specifically what a researcher attempting to replicate this work would need to know that is not currently specified.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "rule-based-check",
    name: "Rule-based check",
    minLevel: 2,
    sequenceTag: "Step 2",
    when: "Output involves a domain where methodological standards or reporting guidelines apply",
    note: "AI frequently generates outputs that are plausible but non-compliant with field-specific standards. The model's knowledge of specific standards varies, so treat its assessment as a starting point and verify against the original standard.",
    text: `I'm going to paste a research output below. Review it against the relevant methodological or reporting standards for this type of work (e.g. PRISMA, CONSORT, APA). Identify any elements that appear non-compliant, missing, or inconsistent with standard practice. Specify which standard or requirement each gap relates to.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model knows what reporting standard was being targeted and can check its own output against it directly.",
      text: `Review the output you just produced against the relevant methodological or reporting standards for this type of work. Identify any elements that appear non-compliant, missing, or inconsistent with standard practice. Specify which standard or requirement each gap relates to.`,
    },
    freshConversation: {
      where: "In a new conversation, ideally a different model",
      whyHere: "A different model may apply the standard more strictly, without any inclination to treat its own output as compliant.",
      text: `I'm going to paste a research output below. Review it against the relevant methodological or reporting standards for this type of work (e.g. PRISMA, CONSORT, APA). Identify any elements that appear non-compliant, missing, or inconsistent with standard practice. Specify which standard or requirement each gap relates to.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "prompt-variation",
    name: "Prompt variation",
    minLevel: 2,
    sequenceTag: "Step 2",
    when: "Output may reflect the framing of the original prompt rather than the underlying evidence",
    note: "Re-prompting with a reframed question can reveal whether the output is stable or sensitive to how the question is asked. Instability is a signal, not proof of a problem.",
    text: `I'm going to paste a research output below. Without knowing what question produced it: (1) describe what this output appears to be claiming; (2) write an alternative framing of what you think the original question was; (3) describe how you would expect the output to differ if that alternative framing had been used instead.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation, then compare",
      whyHere: "Ask the model to re-answer using a reframed version of your question, then compare the two outputs for meaningful differences.",
      text: `I'd like to test whether my output is sensitive to how the question was framed. Please re-answer my original question using this alternative framing: [WRITE YOUR REFRAMED QUESTION HERE]. Then note any meaningful differences between this answer and the one you gave before.`,
    },
    freshConversation: {
      where: "In a new conversation (required for an unbiased read)",
      whyHere: "A fresh session without the original question allows the model to infer what was asked from the output alone, making framing effects visible.",
      text: `I'm going to paste a research output below. Without knowing what question produced it: (1) describe what this output appears to be claiming; (2) write an alternative framing of what you think the original question was; (3) describe how you would expect the output to differ if that alternative framing had been used instead.

[PASTE OUTPUT HERE]`,
    },
  },

  // ── Step 3 ──────────────────────────────────────────────────────────────────

  {
    id: "computational-check",
    name: "Computational check",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output includes numerical results, calculations, or quantitative conclusions",
    note: "AI can silently make arithmetic or unit errors that are consistent with the surrounding text. This probe asks the model to re-derive results independently, which can reveal discrepancies but does not guarantee correctness.",
    text: `I'm going to paste a research output with numerical results below. Before reading it, work through the same calculation independently, showing all steps. Then compare your result with the output and flag any discrepancies, in the answer, intermediate steps, units, or rounding.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In a new conversation (required)",
      whyHere: "The original conversation will reproduce the same result. A fresh session is the only way this check is meaningful.",
      text: `I'm going to paste a research output with numerical results below. Before reading it, work through the same calculation independently, showing all steps. Then compare your result with the output and flag any discrepancies, in the answer, intermediate steps, units, or rounding.

[PASTE OUTPUT HERE]`,
    },
    freshConversation: {
      where: "In a new conversation (required)",
      whyHere: "The original conversation will reproduce the same result. A fresh session is the only way this check is meaningful.",
      text: `I'm going to paste a research output with numerical results below. Before reading it, work through the same calculation independently, showing all steps. Then compare your result with the output and flag any discrepancies, in the answer, intermediate steps, units, or rounding.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "rerunnability-check",
    name: "Rerunnability check",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output is an analysis pipeline, script, or data processing procedure that should be independently reproducible",
    note: "This focuses on whether the output contains enough information to be independently rerun, not whether the results are correct. Gaps in rerunnability are a separate failure mode from numerical error.",
    text: `I'm going to paste an analysis pipeline or code output below. Identify any steps, parameters, dependencies, or data inputs that are not fully specified and would prevent an independent researcher from rerunning this from scratch. Flag anything that would require assumptions or guesswork to reproduce.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can identify what it implicitly assumed or left out when generating the pipeline, dependencies it knew but did not state.",
      text: `Review the analysis pipeline or code you just produced. Identify any steps, parameters, dependencies, or data inputs that are not fully specified in the output and would prevent an independent researcher from rerunning this from scratch. Flag anything that would require assumptions or guesswork to reproduce.`,
    },
    freshConversation: {
      where: "In a new conversation, ideally a different model",
      whyHere: "A model approaching the pipeline as a new user will find underspecification that the original model treated as obvious.",
      text: `I'm going to paste an analysis pipeline or code output below. Identify any steps, parameters, dependencies, or data inputs that are not fully specified and would prevent an independent researcher from rerunning this from scratch. Flag anything that would require assumptions or guesswork to reproduce.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "citation-verification",
    name: "Citation verification",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output includes references and primary sources are available to check",
    note: "This targets both fabricated references and citation misuse, where a real paper is cited but does not support the stated claim. Both failure modes are common. The model cannot independently verify that a source exists. Treat its assessment as a prompt to investigate, not a confirmation. Always check citations yourself.",
    text: `I'm going to paste a research output with citations below. For each reference, list: (1) whether the source exists; (2) whether the author, title, year, and journal are correct; (3) whether the source actually supports the specific claim it is used to support. Treat each citation as a separate item and be explicit when you are uncertain.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can flag citations it is uncertain about. It may know which references it confabulated versus retrieved confidently.",
      text: `Go through the citations in the output you just produced. For each reference, state: (1) your confidence that the source exists; (2) whether the author, title, year, and journal are correct to your knowledge; (3) whether the source actually supports the specific claim it is used to support. Flag any citation where you are uncertain about any of these.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A different model provides an independent check on whether each citation is real and correctly attributed.",
      text: `I'm going to paste a research output with citations below. For each reference, list: (1) whether the source exists; (2) whether the author, title, year, and journal are correct; (3) whether the source actually supports the specific claim it is used to support. Treat each citation as a separate item and be explicit when you are uncertain.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "source-verification",
    name: "Source verification",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output makes factual or interpretive claims that can be checked against primary literature or data",
    note: "This asks the model to identify what verification would require, making the work explicit. It does not perform the verification. That requires human follow-through.",
    text: `I'm going to paste a research output below. For each major claim, identify the primary source or sources that would be needed to verify it. Where no source is cited, flag the claim as unverified. Where a source is cited, state what that source would need to say for the claim to hold as written.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can identify which claims it made confidently versus which it generated without a clear source in mind.",
      text: `Go through the major claims in the output you just produced. For each one, identify the primary source or sources that would be needed to verify it. Where you did not cite a source, flag the claim as unverified. Where you cited a source, state what that source would need to say for the claim to hold as written.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A model reading the output cold will identify verification requirements without being anchored to the sources it originally drew on.",
      text: `I'm going to paste a research output below. For each major claim, identify the primary source or sources that would be needed to verify it. Where no source is cited, flag the claim as unverified. Where a source is cited, state what that source would need to say for the claim to hold as written.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "convergence-check",
    name: "Convergence check",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output is a hypothesis, research direction, or novel framing",
    note: "AI hypothesis generation tends to undersample genuinely novel directions. This probe shows where the model may have anchored and what space remains unexplored.",
    text: `I'm going to paste a hypothesis or research direction below. Identify: (1) the closest analogues in published research, naming specific work where possible; (2) what this direction extends, recombines, or reframes from prior work; (3) adjacent or contrasting directions that were not explored and why they might matter.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can identify the prior work it was drawing on and flag where its generation converged on familiar territory.",
      text: `Look back at the hypothesis or research direction you just produced. Identify: (1) the closest analogues in published research, naming specific work where possible; (2) what this direction extends, recombines, or reframes from prior work; (3) adjacent or contrasting directions you did not explore and why they might matter.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A different model will map the hypothesis against its own knowledge of the literature, potentially identifying different anchoring points.",
      text: `I'm going to paste a hypothesis or research direction below. Identify: (1) the closest analogues in published research, naming specific work where possible; (2) what this direction extends, recombines, or reframes from prior work; (3) adjacent or contrasting directions that were not explored and why they might matter.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "known-literature-test",
    name: "Known-literature test",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "Output makes claims about an established body of literature and the researcher can check against known results",
    note: "Testing an AI output against results you already know is a limited but practical check. Agreement does not confirm accuracy across the whole output; disagreement is a clear signal to investigate further.",
    text: `I'm going to paste a research output and a set of known results I can verify. Compare the output's claims against these known results: [ADD YOUR KNOWN REFERENCES OR FINDINGS HERE]. Note any agreement, discrepancy, or omission, and describe what each discrepancy suggests about the reliability of the claims you cannot independently verify.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can compare its claims directly against the known results you provide, with access to the reasoning behind its original output.",
      text: `I'm going to give you some results I can independently verify. Compare what you said in your previous output against these: [ADD YOUR KNOWN REFERENCES OR FINDINGS HERE]. Note any agreement, discrepancy, or omission, and describe what each discrepancy suggests about the reliability of what you said that I cannot independently verify.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A different model provides an independent check on whether the output's claims align with the known results you supply.",
      text: `I'm going to paste a research output and a set of known results I can verify. Compare the output's claims against these known results: [ADD YOUR KNOWN REFERENCES OR FINDINGS HERE]. Note any agreement, discrepancy, or omission, and describe what each discrepancy suggests about the reliability of the claims you cannot independently verify.

[PASTE OUTPUT HERE]`,
    },
  },

  {
    id: "uncertainty-surfacing",
    name: "Uncertainty surfacing",
    minLevel: 3,
    sequenceTag: "Step 3",
    when: "No verification object is available and the output involves claims that cannot be checked against external material",
    note: "When verification against sources is not possible, mapping the extent of uncertainty is the most useful available check. This prompt does not verify anything. It maps what is unknown.",
    text: `I'm going to paste a research output below. For each major claim or conclusion, describe: (1) what you would need to know to be confident this is correct; (2) what assumptions are being made without that information; (3) how the output would change if those assumptions are wrong. Do not attempt to resolve the uncertainty. Describe its shape and extent.

[PASTE OUTPUT HERE]`,
    inConversation: {
      where: "In the original conversation",
      whyHere: "The model can describe the uncertainty behind each claim from the inside, what it was unsure of when generating it, not just what looks uncertain from the text.",
      text: `For each major claim or conclusion in the output you just produced, describe: (1) what you would need to know to be confident it is correct; (2) what assumptions you made without that information; (3) how the output would change if those assumptions are wrong. Do not attempt to resolve the uncertainty. Describe its shape and extent.`,
    },
    freshConversation: {
      where: "In a new conversation or a different model",
      whyHere: "A model reading the output without context will map uncertainty from the outside, which may surface different gaps than the original model would identify.",
      text: `I'm going to paste a research output below. For each major claim or conclusion, describe: (1) what you would need to know to be confident this is correct; (2) what assumptions are being made without that information; (3) how the output would change if those assumptions are wrong. Do not attempt to resolve the uncertainty. Describe its shape and extent.

[PASTE OUTPUT HERE]`,
    },
  },
];
